name = "skipper-api"
main = "src/index.ts"
compatibility_date = "2026-04-20"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[vars]
APP_ENV = "production"
STOREFRONT_ORIGIN = "https://skipperdetergents.pages.dev,http://localhost:5173"
ADMIN_ORIGIN = "https://skipper-admin.pages.dev,http://localhost:5174"

[[d1_databases]]
binding = "DB"
database_name = "skipper-detergents-db"
database_id = "4d774420-93b4-45cf-905d-e9313006aafc"
migrations_dir = "./src/db/migrations"

[[r2_buckets]]
binding = "R2_PRODUCTS"
bucket_name = "skipper-products"

[[r2_buckets]]
binding = "R2_PROOFS"
bucket_name = "skipper-payment-proofs"

[[kv_namespaces]]
binding = "KV_SESSIONS"
id = "a511f9a50cc046f1ba99aa6a7c73ed9d"

[[kv_namespaces]]
binding = "KV_RATE_LIMIT"
id = "d30776a368924a4b83b7f9bd996d65bf"

[[kv_namespaces]]
binding = "KV_CACHE"
id = "c82c3eab55e644ce8f252be041d82b93"
